### PR TITLE
Refine NGAP handler

### PR DESCRIPTION
**Pull request by ShouheiNishi**
- Replace NGAP message dispatch and IE fetch in the first part of NGAP handler with code automatically generated from ASN.1 file.
- Check IE for missing and duplicate and perform error handling.
- Implemented handling of UE IDs in accordance with TS 38.413 "10.6 Handling of AP ID"

### CODE REVIEW

**Review by tim-ywliu — APPROVED** [review]

**Comment by ss920386** [comment]
@ShouheiNishi Excuse me if this comment duplicates with a previous one I left in ngap_generator.go which I can't find anymore for unknown reason. 
I saw in ngap_generator.go you commented out `// if e['criticality'].lower() == 'reject':` for building error indication when mandatory IEs were not present. May I ask for your concern to comment it out? Without this check, AMF rejected the procedure when the missing IE's criticality is _ignore_, which I think is not expected. Thanks.

**Comment by ShouheiNishi** [comment]
> @ShouheiNishi Excuse me if this comment duplicates with a previous one I left in ngap_generator.go which I can't find anymore for unknown reason. I saw in ngap_generator.go you commented out `// if e['criticality'].lower() == 'reject':` for building error indication when mandatory IEs were not present. May I ask for your concern to comment it out? Without this check, AMF rejected the procedure when the missing IE's criticality is _ignore_, which I think is not expected. Thanks.

I decided that mandatory takes precedence in mandatory and ignore IE processing, and commented that part. After re-consideration, I've decided that missing Mandatory and ignore IE should be tolerated, so I will fix it.
However, the fix may cause many arguments of the function in handler.go to be nil, and we need to add a check for that, so it will take some time to fix.

**Comment by ss920386** [comment]
> 

Get it. Thanks for your effort!

**Comment by ShouheiNishi** [comment]
> > 
> 
> Get it. Thanks for your effort!

We create PR https://github.com/free5gc/amf/pull/90.

**Pull request merged**
