### PR TITLE
LogLevel is not applied when the test is run.

### PR DESCRIPTION
**Pull request by RyuichiNamba-fj**

### CODE REVIEW

**Comment by RyuichiNamba-fj** [comment]
@free5gc-org 
As shown above, golangci-lint was failed.
It was also failed in main branch.
Could you please check to see if there is a problem with the setup?

**Comment by free5gc-org** [comment]
@RyuichiNamba-fj 

Please try to add it under steps in .github/workflows/golangci-lint.yml:
```
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.4'
```

**Comment by RyuichiNamba-fj** [comment]
@free5gc-org 
I tried to add the suggested action, but failed. 
But, I was able to test it successfully by adding the following(★)
```
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.4'
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.35.0
          skip-go-installation: true ★
```

Should I submit a PR for this? Or do you want to modify it there?

**Comment by free5gc-org** [comment]
@RyuichiNamba-fj 

Great! You can commit this fix in this PR.

**Comment by RyuichiNamba-fj** [comment]
@free5gc-org 
I commited fix. 
I'll commit the fix other submodules as well.

**Comment by RyuichiNamba-fj** [comment]
@free5gc-org 
I commited the fix other submodules.

**Review by free5gc-org — APPROVED** [review]

**Pull request merged**
