### PR TITLE
AMF panics on receiving Deregistration Request after receiving UEContextReleaseComplete

### PR DESCRIPTION
**Pull request by RyuichiNamba-fj**

### CODE REVIEW

**Review by free5gc-org — COMMENTED** [review]
The root cause is there are 2 ranUe contexts binding to 1 amfUe context, but amfUe context already connects to the new ranUe.
When receiving UEContextReleaseComplete, the old ranUe to set amfUe.ranUe to nil.
The better way is the old ranUe should check the amfUe.ranUe is the same one by RANUEID before setting it to nil.

**Comment by RyuichiNamba-fj** [comment]
@free5gc-org 
>The better way is the old ranUe should check the amfUe.ranUe is the same one by RANUEID before setting it to nil.

Yes, I am also aware of this issue and will provide a PR for it later.

>Thus, the Deregistration Accept still can be sent from amfUe and new ranUe contexts.

By applying the above PR, which will be provided later, this problem will almost disappear, but I think it is better to take this change just in case.

**Review by tim-ywliu — APPROVED** [review]

**Comment by free5gc-org** [comment]
@RyuichiNamba-fj 
We have a new patch for it.
Could you get the latest commit (61de502ba16aa2a58be3723740206f3df3c2d488) on amf main branch to test it again?

**Comment by RyuichiNamba-fj** [comment]
@free5gc-org 
I tested it with the latest version and got the following error:
`[ERRO] [AMF] [GMM] SendDeregistrationAccept: RanUe is nil`

Attach the console log and pcap file.
I think RanUE needs to be checked before Send DeregistrationAccept.
[20210726_test.zip](https://github.com/free5gc/amf/files/6875747/20210726_test.zip)

**Comment by free5gc-org** [comment]
@RyuichiNamba-fj 
We have a new fix for SendDeregistrationAccept.
Could you get the latest commit (42633d000965476d2685956d24c3e7d450e6f1a0) on amf main branch to test it again?
Thanks.

**Pull request merged**
